spring.application.name=TemperatureAPI
server.port=8082
# Izaberi mjernu jedinicu: C or K
temperature.unit=C
temperature.service.url=http://temperature-app:8080
humidity.service.url=http://humidity-app:8081
